### ISSUE TITLE
terminating workers

### ISSUE THREAD

**Issue by riccardopinosio** [vladopajic/go-actor-examples#2]
Hello, I've been looking at the library and I have a query. Consider the following example

```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/vladopajic/go-actor/actor"
)

type produceWorker struct {
	mailbox actor.Mailbox[string]
	num     int
	l       []string
}

type consumerWorker struct {
	inMbx actor.Mailbox[string]
	id    int
}

func (w *produceWorker) DoWork(c actor.Context) actor.WorkerStatus {
	if w.num < len(w.l) {
		w.mailbox.SendC() <- w.l[w.num]
		w.num++
		return actor.WorkerContinue
	}
	return actor.WorkerEnd
}

func (w *consumerWorker) DoWork(c actor.Context) actor.WorkerStatus {
	select {
	case s := <-w.inMbx.ReceiveC():
		fmt.Printf("consumed %s \t(worker %d)\n", s, w.id)
		return actor.WorkerContinue

	case <-c.Done():
		return actor.WorkerEnd
	}
}

func main() {
	mailbox := actor.NewMailbox[string]()
	pw := &produceWorker{mailbox: mailbox, l: []string{"A", "B", "C"}}
	cw := &consumerWorker{inMbx: mailbox, id: 1}

	a := actor.Combine(
		mailbox,
		actor.New(pw),
		actor.New(cw),
	)
	a.Start()
	defer a.Stop()
	<-WaitForTermination()
}

func WaitForTermination() <-chan struct{} {
	sig := make(chan os.Signal, 1)
	done := make(chan struct{})

	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-sig
		close(done)
	}()

	return done
}
```

I am trying to replicate the examples in the example folder (btw it looks as if the examples are outdated as they use mailbox.Send/SendReceiver but these methods don't exist?), but what i would like to achieve is for the producer to sent strings into the mailbox (A, B, C above) and then terminate, and for the consumer to grab these strings, print them, and then terminate. The example above works in that the strings are generated and printed, but afterwards the program doesn't terminate. Could you point me into the direction of what I'm missing here? Thanks :)

**Comment by vladopajic** [comment]
program is not terminated because it keeps waiting or termination signal CTRL+C. in order to terminate on some other signal you'll need to add it together with `WaitForTermination`, eg:

```
	select {
	case <-doneSigC:
	case <-WaitForTermination():
	}
```

here `doneSigC` is channel that is added to consumer which will send signal to it when everything was produced & consumed.


full example:
```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/vladopajic/go-actor/actor"
)

type produceWorker struct {
	mailbox actor.Mailbox[string]
	num     int
	l       []string
}

type consumerWorker struct {
	inMbx    actor.Mailbox[string]
	doneSigC chan struct{}
	id       int
}

func (w *produceWorker) DoWork(c actor.Context) actor.WorkerStatus {
	if w.num < len(w.l) {
		w.mailbox.Send(c, w.l[w.num])
		w.num++
		return actor.WorkerContinue
	}
	return actor.WorkerEnd
}

func (w *consumerWorker) OnStop() {
	close(w.doneSigC) // send done sig, option A (better)
}

func (w *consumerWorker) DoWork(c actor.Context) actor.WorkerStatus {
	select {
	case s := <-w.inMbx.ReceiveC():
		if s == "END" {
			// close(w.doneSigC) // send done sig, option B
			return actor.WorkerEnd
		}
		fmt.Printf("consumed %s \t(worker %d)\n", s, w.id)
		return actor.WorkerContinue

	case <-c.Done():
		return actor.WorkerEnd
	}
}

func main() {
	mailbox := actor.NewMailbox[string]()
	pw := &produceWorker{mailbox: mailbox, l: []string{"A", "B", "C", "END"}}
	cw := &consumerWorker{inMbx: mailbox, id: 1, doneSigC: make(chan struct{})}

	a := actor.Combine(
		mailbox,
		actor.New(pw),
		actor.New(cw),
	)
	a.Start()
	defer a.Stop()

	select {
	case <-cw.doneSigC:
	case <-WaitForTermination():
	}
}

func WaitForTermination() <-chan struct{} {
	sig := make(chan os.Signal, 1)
	done := make(chan struct{})

	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-sig
		close(done)
	}()

	return done
}
```

---

> btw it looks as if the examples are outdated as they use mailbox.Send/SendReceiver but these methods don't exist?

could you please git pull and is if this gets resolved?

**Comment by riccardopinosio** [comment]
Ok cool, then if I understand correctly in your example above, the steps are (1) the producer sends a "done" signal to the consumer ("END"), which then (2) leads the consumer to also end, and (3) the OnStop function closes the doneSigC channel, which then (4) terminates the program.

On the methods, I can get the right methods if I put version 0.7.1 in go.mod, but by default with go get it pulls version 1.0.5, which however looks to be older (from end of last year) and doesn't have the right methods.

**Comment by vladopajic** [comment]
> Ok cool, then if I understand correctly in your example above, the steps are (1) the producer sends a "done" signal to the consumer ("END"), which then (2) leads the consumer to also end, and (3) the OnStop function closes the doneSigC channel, which then (4) terminates the program.

correct. this is one option, however there could be other options, like consumer can close `doneSigC` after some timeout if there is nothing in it's mailbox.

```
func (w *consumerWorker) DoWork(c actor.Context) actor.WorkerStatus {
	select {
	case <-time.After(time.Second*5): // if consumer doesn't receive data in mailbox in 5sec, consider all messages consumed.
               return actor.WorkerEnd 
	case s := <-w.inMbx.ReceiveC():
		fmt.Printf("consumed %s \t(worker %d)\n", s, w.id)
		return actor.WorkerContinue

	case <-c.Done():
		return actor.WorkerEnd
	}
}
```

**Comment by riccardopinosio** [comment]
Ok it's all clear!
